# 配置项目信息
spring:
  application:
    name: cloud-common
#  security:
#    user:
#      name: root
#      password: root
server:
  port: 8000


# zipkin 需要配置的
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eurekaServer:
  host: 127.0.0.1
  port: 9000

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    fetch-registry: false
    # eureka 注册中心服务地址
    service-url:
      defalutZone: http://${eurekaServer.host}:${eurekaServer.port}/eureka
  #      defalutZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.server.host}:${eureka.server.port}
  instance:
    prefer-ip-address: true
# redis 配置
#redis:
#  host: 127.0.0.1
#  port: 6000
#  #  password:
#  database: 1
#  timeout: 10*1000
#  lettuce:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0