# 配置项目信息
spring:
  application:
    name: cloud-common
  sleuth:
    enabled: false
  rabbitmq:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin_data?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
    schema: classpath:sql/zipkin.sql
    dbcp2:
      #初始化连接:连接池启动时创建的初始化连接数量
      initial-size: 50
      #从连接池获取一个连接时，最大的等待时间,连接池会等待N毫秒，等待不到，则抛出异常
      max-wait-millis: 60000
      #最大空闲连接:连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
      max-idle: 100
      #通过这个池创建连接的默认自动提交状态。如果不设置，则setAutoCommit 方法将不被调用
      default-auto-commit: true
      #通过这个池创建连接的默认只读状态
      default-read-only: false
      #指明在从池中租借对象时是否要进行验证有效，如果对象验证失败，则对象将从池子释放，然后我们将尝试租借另一个
      test-on-borrow: true
    type: org.apache.commons.dbcp2.BasicDataSource
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    schema: classpath*:sql/zipkin.sql
#    url: jdbc:mysql://127.0.0.1:3306/zipkin_data?userUnicode=true&characterEncoding=utf8&autoReconnect=true
#    username: root
#    password: root
#    initialization-mode: always
#    initialize: true

#druid:
#  enable: true
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/zipkin_data?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#  security:
#    user:
#      name: root
#      password: root
server:
  port: 8000
# zipkin server 持久方式
zipkin:
  storage:
    type: mysql
# zipkin server 这个配置一定要加，不然打不开 web-ui控制台
management:
  metrics:
    web:
      server:
        auto-time-requests: false
#eureka 配置信息
eurekaServer:
  host: 127.0.0.1
  port: 9000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.host}:${eurekaServer.port}/eureka

# 配置日志文件 地址
logging:
  config: classpath:log4j2-spring.xml

# redis 配置
#redis:
#  host: 127.0.0.1
#  port: 6000
#  #  password:
#  database: 1
#  timeout: 10*1000
#  lettuce:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0