# 配置项目信息
spring:
  application:
    name: cloud-common
#  security:
#    user:
#      name: root
#      password: root
server:
  port: 8000


# zipkin 需要配置的
zipkin:
  base-url: http://127.0.0.1:8000/
  locator:
    discovery:
      enabled: true
  service:
    name: 127.0.01 #zipkin
locator:
  discovery:
    enabled: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
#eureka 配置
eurekaServer:
  host: 127.0.0.1
  port: 9000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.host}:${eurekaServer.port}/eureka
# redis 配置
#redis:
#  host: 127.0.0.1
#  port: 6000
#  #  password:
#  database: 1
#  timeout: 10*1000
#  lettuce:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0