# 配置项目名称
spring:
  application:
    name: SpringCloudDemoProvider
  # zipkin 客户端配置信息
  zipkin:
    base-url: http://127.0.0.1:8000
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8081
# =====================================
# 自定义变量
user:
  name: geekswg
  email: geekswg@qq.com
  age: 28
  defaultName: shiwanggui
# =====================================
# 配置 Eureka
eurekaServer:
  host: 127.0.0.1
  port: 9000
  user: root
  password: root
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.host}:${eurekaserver.port}/eureka
#      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaserver.port}/eureka

##
#监控应用名称 唯一
#限制白名单 访问监控端点 为空则不限制  建议设置
actuator.server.ip:
#监控远程应用日志
actuator.log.path: D:/log/boot-monitor/spring.log

# DataSource Config
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/db_geek?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
  username: root
  password: root
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql