spring:
  application:
    name: eureka-server
  security:

    user:
      name: root
      password: root

server:
  host: 127.0.0.1
  port: 9000


eureka:
  server:
    enable-replicated-request-compression: false
  client:
    #此项目不作为客户端注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://${server.host}:${server.port}/eureka
      #defalutZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.host}:${server.port}/eureka

    #此处设置会改变eureka控制台的显示
    datacenter: cloud
    #此处设置会改变eureka控制台的显示
    environment: prod
    dashboard:
      #控制台路径
      path: /dashboard
      #是否启用控制台
      enabled: true
    instance:
      #实例主机名
      hostname: 127.0.0.1
    security:
      basic:
        #关闭安全验证
        enabled: false

