spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root

server:
  host: 127.0.0.1
  port: 9000


eureka:
  server:
    enable-replicated-request-compression: false
  client:
    #此项目不作为客户端注册
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://${server.host}:${server.port}/eureka


